# Generated by Django 5.0.6 on 2024-06-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField()),
                ('ready', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('for_sale', models.BooleanField(default=False)),
                ('for_rent', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.region'),
        ),
        migrations.AddField(
            model_name='region',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.state'),
        ),
    ]
