# Generated by Django 5.0.6 on 2024-06-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_owner_region_name_english_state_name_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
    ]
