# Generated by Django 5.0.6 on 2024-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_house_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='region',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='state',
            name='sequence',
            field=models.IntegerField(default=100),
        ),
    ]
