# Generated by Django 5.0.6 on 2024-06-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_house_main_image_image_sequence_region_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
