# Generated by Django 5.0.6 on 2024-06-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_message_house_sell_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='sell_price',
            new_name='sale_price',
        ),
    ]
