# Generated by Django 5.0.6 on 2024-06-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sell_price_house_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
