# Generated by Django 5.0.6 on 2024-06-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_house_date_message_date_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
