# Generated by Django 5.0.1 on 2024-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_house_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
