# Generated by Django 5.0.6 on 2024-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_house_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='private_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
