# Generated by Django 5.0.6 on 2024-06-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_house_private_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'initialized'), (2, 'done'), (3, 'canceled')], default=1),
        ),
    ]
