# Generated by Django 5.1.4 on 2025-01-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='special',
        ),
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.TextField(choices=[('1', 'سكني'), ('2', 'تجاري'), ('3', 'زراعي')], null=True),
        ),
    ]
