# Generated by Django 5.1.4 on 2025-01-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_house_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='unit',
            field=models.CharField(default='م', max_length=50),
        ),
    ]
