# Generated by Django 5.1.4 on 2025-01-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_house_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='unit',
        ),
    ]
